<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-1G02M72B" failures="1" tests="5" name="Command line test" time="65.435" errors="0" timestamp="29 Nov 2022 22:17:16 GMT">
  <testcase classname="com.salesforce.tests.LoginTest" name="forgotpassword" time="1.628">
    <failure type="java.lang.AssertionError" message="expected [We’ve sent you an email with a link to finish resetting your password.] but found [Weâ€™ve sent you an email with a link to finish resetting your password.]">
      <![CDATA[java.lang.AssertionError: expected [We’ve sent you an email with a link to finish resetting your password.] but found [Weâ€™ve sent you an email with a link to finish resetting your password.]
at com.salesforce.tests.LoginTest.forgotpassword(LoginTest.java:92)
... Removed 40 stack frames]]>
    </failure>
  </testcase> <!-- forgotpassword -->
  <testcase classname="com.salesforce.tests.LoginTest" name="forgotpasswordB" time="0.679"/>
  <testcase classname="com.salesforce.tests.LoginTest" name="loginFail" time="2.827"/>
  <testcase classname="com.salesforce.tests.LoginTest" name="loginSuccess" time="0.476"/>
  <testcase classname="com.salesforce.tests.LoginTest" name="usernamecheck" time="14.796"/>
</testsuite> <!-- Command line test -->
